language: node_js
node_js:
  - "node"
warnings_are_errors: false
install:
  - npm install
  - npm install -g firebase-tools
  - npm install bootstrap

script:
  - unset CI 
  - npm run build
deploy:
  project: default
  provider: firebase
  token: $FIREBASE_TOKEN
  on:
    tags: false
    all_branches: false
